language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: clairguraik-github
    token: 88fba1f017983f5685c5afdf501aecd2f36dd0b4
      secure:
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'